{% set version = "0.8" %}
{% set name = "rw" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://excellmedia.dl.sourceforge.net/project/rankwidth/{{ name }}-{{ version }}.tar.gz
  sha256: 60fd5320bef28a5156284fc224534376405f2655c6777a12a05fcacc0576d700

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - libtool
    - automake
    - pkg-config
    - {{ compiler('c') }}
  host:
    - m4
    - igraph 0.7.*

  run:
    - igraph 0.7.*

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib     # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so        # [linux]

about:
  home: https://sourceforge.net/projects/rankwidth/
  license: GPLv2
  license_file: COPYING
  summary: rw calculates rank-width and rank-decompositions
  dev_url: https://sourceforge.net/p/rankwidth/code/HEAD/tree/

extra:
  recipe-maintainers:
    - isuruf
