travis:
  secure:
    BINSTAR_TOKEN: q1dlbko8Fx8jTMLcXj5KNgeFUneEIJfguTJdaEqKiE6o1NQy0eoc9ZnLEcnTSie9L/P535vec/EeqNN8ZND5qK/EdB14Q/trE2RCyVBhwXOGFoq0yVe+/+cSA878wlRsztLa/P5MiGbbR95L7EMVCvzDTiWtESXUnMUJFUJNdibkYoJGayNdFffEyx6DYWET6hK76nRq2MJmewqXZWT1eo5z100UboY3iP1MQcNNjCYhRpjAUArFygCqEXARfVDJLST37UckAUymDjNZdWDg4mp76er/N3vH3IDKYODARgOB5jkLVjkZRbaGWj97gMcWCuKBS9ZWc/v76T3gMGlkiOfej/wYim+R2GoB2lbpiHnUxl+Ufkq9+VF4bPUvuDkygKw7k0yAZDpMr5PxMPzS4+RdILJHO3FWinhyocE3brqDhCwsi1pvJk2t9gC4gGoXSmoFjIexmDafFlvpemUBBXhVmut9nxqQw24IzMzcShM+hVxZSTjQYiQIIL1UCmRgcKt8LnrWr/enK5aGHprttBXP+GBpAHAotYIee/mfsVCag2/GgAKzA4Oxe7E2z2w9gWOCTwR9Ho25O3If9yST2XhQVsLcpO8DvRbzvbQ5gleyb6josbbhTcd903+Xw5CGotpUxnJFHGdRhiQQRDhuKjL1SIohItUBOHmCGCrKwVE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
