appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: QiYSAu/OwPSSKJ26bHdWH1ytsnOm8AfGr+joEWon2IF5umR484u6VJH3XlD5gue+ZbtfWulPWxfn4+5KG9o1P4v1lrQm3w82vHTukcEM2iN7Linj/OuniKSSodZMnmAv8gCnVMIv6Q47nk429LhmhReFKO6t+tiY+lA7fgRW79e7w0Z595zmhxHR5FK+LSIU/XZj0oPi/KmI96K17lbYq/jE8yBfrCsaAV3ecdsiZb3obDMIjct9/J4RFDvh6PdWGvgxmhEwVa7nb8l6oZ9n5wvITKqddsJt5rLKNybGDiKStPkIYjNE/KDhJXAKWYXMloSahQsMlpku0g/9Let4IzUSECztcTDEKd7l1sk3tvAhxA/39XmD96lKIy897cLv4dOM7AGajW15OQo27WNpnQmUA3X8SiYoWr+m7KydzBO2C1z+cuk86l8riwz7cmqwZzt7xKlJAaqYd22KulWKFtJQ9UH7SXAxXA61D4gfIib2ZI0RrDu7i+/OlKXLxh5zPvcKwA1/whpVDJq/3TDIIpyFTotQKBUKmSS44t2bikNI8RhHkTixWOHb27cG16yVpqRvIATEijJwsjgsO0+EXRF5XTcLjver3uY+q19txowPTn+4njRdllm96cVitsZ8Xl+jxpbt9ZFfBQUxNNaIOb1MPm8xECZYc4K+Q7XTn3k=}
